/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  EInvoice as PrismaEInvoice,
  Order as PrismaOrder,
} from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class EInvoiceServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(args: Omit<Prisma.EInvoiceCountArgs, "select">): Promise<number> {
    return this.prisma.eInvoice.count(args);
  }

  async eInvoices(
    args: Prisma.EInvoiceFindManyArgs
  ): Promise<PrismaEInvoice[]> {
    return this.prisma.eInvoice.findMany(args);
  }
  async eInvoice(
    args: Prisma.EInvoiceFindUniqueArgs
  ): Promise<PrismaEInvoice | null> {
    return this.prisma.eInvoice.findUnique(args);
  }
  async createEInvoice(
    args: Prisma.EInvoiceCreateArgs
  ): Promise<PrismaEInvoice> {
    return this.prisma.eInvoice.create(args);
  }
  async updateEInvoice(
    args: Prisma.EInvoiceUpdateArgs
  ): Promise<PrismaEInvoice> {
    return this.prisma.eInvoice.update(args);
  }
  async deleteEInvoice(
    args: Prisma.EInvoiceDeleteArgs
  ): Promise<PrismaEInvoice> {
    return this.prisma.eInvoice.delete(args);
  }

  async uploadFile<T extends Prisma.EInvoiceFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.EInvoiceFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaEInvoice> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "file";
    const file = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.eInvoice.update({
      where: args.where,

      data: {
        file: file as InputJsonValue,
      },
    });
  }

  async downloadFile<T extends Prisma.EInvoiceFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.EInvoiceFindUniqueArgs>
  ): Promise<FileDownload> {
    const { file } = await this.prisma.eInvoice.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      file as unknown as LocalStorageFile
    );
  }

  async deleteFile<T extends Prisma.EInvoiceFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.EInvoiceFindUniqueArgs>
  ): Promise<PrismaEInvoice> {
    const { file } = await this.prisma.eInvoice.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      file as unknown as LocalStorageFile
    );

    return await this.prisma.eInvoice.update({
      where: args.where,

      data: {
        file: Prisma.DbNull,
      },
    });
  }

  async getOrder(parentId: string): Promise<PrismaOrder | null> {
    return this.prisma.eInvoice
      .findUnique({
        where: { id: parentId },
      })
      .order();
  }
}
